apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    io.kompose.service: api-gateway
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
spec:
  type: NodePort           
  selector:
    io.kompose.service: api-gateway
  ports:
    - name: "http"
      port: 8000
      targetPort: 8000
      nodePort: 30080    
