apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: restaurant-service
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: restaurant-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: restaurant-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: restaurant-service--env
          image: restaurant-service
          name: restaurant-service
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
