apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: user-management-service
  name: user-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-management-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: user-management-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: user-management-service--env
          image: user-management-service
          name: user-management-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
